version: '2'

services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      - ./puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - ./puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/
      - ./puppet-conf/puppet.conf:/etc/puppetlabs/puppet/puppet.conf
      - ./hiera-global/hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml
      - ./facts/facts.yaml:/etc/puppetlabs/facts.yaml
